title: My Resume
url: 'https://steviesaps.github.io/steviesaps.github.io/'
baseurl: 'Stevie Saponja CV' #change it according to your repository name
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
